### ISSUE TITLE
Tracking issue for v2

### ISSUE THREAD

**Issue by andersevenrud** [andersevenrud/xpra-html5-client#3]
This was moved from the README file.

* Xpra library
  * [x] Connectivity
  * [x] Authentication
  * [ ] Encryption (**WIP**)
  * [x] Capability detection
  * [x] Packet decoding and proxying
  * [x] Error handling
  * [x] Window handlers
  * [x] Cursor handlers
  * [x] Sound handlers
  * [x] Keyboard handlers
  * [x] Mouse handlers
  * [x] Notifications
  * [x] Clipboard
  * [x] Download/Upload
  * [x] Print
  * [x] Remote logging
  * [x] Bell
  * [x] Tray
  * [x] Webworker
  * Rendering support
    * [x] Direct rendering
    * [ ] Offscreen canvas
    * Formats
      * [x] PNG/JPEG/WebP
      * [x] RGB32/RGB24
      * [x] AVIF
      * [ ] MPEG1
      * [ ] MPEG4
      * [ ] h264
      * [ ] VP8
      * [x] Void
      * [x] Scroll
* UI
  * [ ] On-screen keyboard
  * [ ] Client-side scaling
  * [ ] Suspend/resume windows
  * [ ] Fullscreen windows
  * [ ] Desktop class back layers
  * [x] Connection options via URL query
  * [x] Connection settings modal
  * [x] Window management
  * [x] Window interaction
  * [x] Cursor support
  * [x] XDG Menu
  * [x] Tray
